/**
 * Create Subscription For OECD Tax Pillar 2 Service
 * A synchronous API that allows MDTP / BTA to post requests to ETMP in order for subscriptions to be created for OECD Pillar 2 customers.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: services.enterpriseintegration@hmrc.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 */
case class DateType (
)

