/**
 * Create Subscription For OECD Tax Pillar 2 Service
 * A synchronous API that allows MDTP / BTA to post requests to ETMP in order for subscriptions to be created for OECD Pillar 2 customers.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: services.enterpriseintegration@hmrc.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param addressLine1 Address Line 1
 * @param addressLine2 Address Line 2
 * @param addressLine3 Address Line 3
 * @param addressLine4 Address Line 4
 * @param postCode Postal code
 * @param countryCode 
 */
case class RequestUpeCorrespAddressDetails (
  addressLine1: String,
  addressLine2: Option[String] = None,
  addressLine3: Option[String] = None,
  addressLine4: Option[String] = None,
  postCode: Option[String] = None,
  countryCode: countryCodeType
)

